default_language_version:
  python: python3
repos:
  - repo: https://github.com/ambv/black
    rev: 25.9.0
    hooks:
      - id: black

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.0.0
    hooks:
      - id: check-byte-order-marker
      - id: check-case-conflict
      - id: check-json
      - id: check-yaml
      - id: end-of-file-fixer
      - id: flake8
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: trailing-whitespace

  - repo: local
    hooks:
      - id: needs-hash
        name: commit message needs issues
        language: pygrep
        entry: '#\d+'
        args: [--multiline, --negate]
        stages: [commit-msg]

      - id: pytest-check
        name: pytest
        language: python
        entry: pytest -q
        types: [python]
        stages: [pre-commit]
        pass_filenames: false
        always_run: true
        additional_dependencies:
          - pytest==8.4.2
